### PR TITLE
Removing component that calls out Insight as special feature. Added a…

### PR DESCRIPTION
**Pull request by tekgrunt**
… section on Org Groups.

## Description of the change

> Changed some content based on new marketing approach as well as adding a section describing a new(er) capability not in the previous iteration.

## Type of change
- [ X] Bug fix (non-breaking change that fixes an issue)
- [X ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]()

### CODE REVIEW

**Comment by Eccentrish** [comment]
I did minor copy/tense/grammar edits
**on either side of sentence below the "OUTPUT" heading -further editing required as the sentence seems unfinished or unnecessary. Otherwise it looks good

**Review by Eccentrish — CHANGES_REQUESTED** [review]
minor copy/tense/grammar edits
**on either side of sentence below the "OUTPUT" heading -further editing required

**Comment by tekgrunt** [comment]
I think we should be good to go.

**Review by Eccentrish — APPROVED** [review]
lgtm

**Pull request merged**
